### ISSUE TITLE
Docgen not working with xunit testresults from wiremock

### ISSUE THREAD

**Issue by carlosriess** [opendevstack/ods-document-generation-svc#42]
When running DocGen it stucks when it runs projects that use wiremock technology in theirs tests..

**To Reproduce**
1-Write a integration test using Spring Boot 2.2.7 that uses wiremock v2.26.3
2-The test should run fine and succesfully.
3-Integrate this project into a Release Manager with DocGen.
4-Run Developer Preview on Jira
5-A SocketTimeOutException exception ocurrs.
**Expected behavior**
All tests should pass and the documentation should be generated
**Troubleshooting**

From Openshift the jenkins pod agent is killed after DocGen sends the response..In DocGen log files there are no errors available.

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 2.0

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at unirest.shaded.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at unirest.shaded.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at unirest.shaded.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at unirest.shaded.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at unirest.shaded.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at unirest.shaded.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at unirest.shaded.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at unirest.shaded.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at unirest.shaded.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at unirest.shaded.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at unirest.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at unirest.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at unirest.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at unirest.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at unirest.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at unirest.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at unirest.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at unirest.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:125)
	at kong.unirest.BaseRequest.asString(BaseRequest.java:180)
	at sun.reflect.GeneratedMethodAccessor10641.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.ods.service.DocGenService.createDocument(DocGenService.groovy:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
Caused: kong.unirest.UnirestException
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:133)
	at kong.unirest.BaseRequest.asString(BaseRequest.java:180)
	at sun.reflect.GeneratedMethodAccessor10641.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.ods.service.DocGenService.createDocument(DocGenService.groovy:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.ods.usecase.DocGenUseCase.createDocument(DocGenUseCase.groovy:32)
	at org.ods.usecase.LeVADocumentUseCase.createDTR(LeVADocumentUseCase.groovy:515)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:291)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:287)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:277)
	at phaseBuild.call(phaseBuild.groovy:41)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:530)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:450)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
Caused: java.lang.IllegalStateException: Error: Creating document of type 'DTR' for project 'xxxx' and repo 'xxxxx-aaaaaa' in phase 'Build' and stage 'POST_EXECUTE_REPO' has failed: java.net.SocketTimeoutException: Read timed out.
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:293)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:287)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:277)
	at phaseBuild.call(phaseBuild.groovy:41)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:530)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:450)
	at ___cps.transform___(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
**Additional context**
If all tests using wiremock are excluded from build then DocGen passes succesfully and documentation is generated.

**Comment by metmajer** [comment]
Thanks, @carlosriess and @alanbort. We will write an automated test for DocGen to prove that the problem exists, then implement a fix in an upcoming version.

**Comment by jssnull** [comment]
Hi,
we have taken an screenshot of the jenkins slave used in this case.
concretely it terminates due to an OOM error:

![image](https://user-images.githubusercontent.com/12979859/94703826-8ee30e00-033f-11eb-990e-a4a9b9b66f25.png)

**Comment by metmajer** [comment]
@jssnull and the sole reason is the content in `system-out`? Well, who knows what the `XMLSlurper` implementation does with the information therein...

**Comment by jssnull** [comment]
yes, maybe the XMLSlurper dependecy is designed for using a fixed limit of XML content, memory or something like that.
Having that, it could be normal if 8k lines of log in system-out could produce the OOM; I'm not completely sure about it, but it could make sense.

**Comment by clemensutschig** [comment]
can you upload the xunit results here? -- (or at least the system out block) - so we can do sth with it`? -- and try to fix it?

**Comment by carlosriess** [comment]
Hi,

Here you have three tests that have system out data in their results....All them three running wiremock.

[system out data.zip](https://github.com/opendevstack/ods-document-generation-svc/files/5475797/system.out.data.zip)

**Comment by clemensutschig** [comment]
so - quick update ... I think I can reproduce this standalone

```
        File xunitresults = new File ("src/test/resources/TEST-......ForwarderClientTest.xml")

        // takes really forever ... (and this is how it's currently done in the levaDocumentUsecase (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy#L535-L537)
        println ("xml based on xmlutil")
        def data = [
            name: "Project Phoenix",
            metadata: [
                header: "header",
                description: XmlUtil.serialize(xunitresults.text) 
            ]
        ]

        // works
        GPathResult xmlResult = new XmlSlurper().parse(xunitresults)
        println ("xml based on slurper")
        def data = [
            name: "Project Phoenix",
            metadata: [
                header: "header",
                description: new XmlNodePrinter().print(xmlResult)
            ]
        ]

```

**Comment by clemensutschig** [comment]
so this may be a bug in the jenkins shared lib actually

**Comment by clemensutschig** [comment]
Ok - update ... I can cleanly reproduce this with 0.12.5.1 of wkhtml (and don't find whats wrong... ) ... with 0.12.6 _ this seems to work, but I get another error ...

**Comment by clemensutschig** [comment]
more fun with this ... on latest 12.6:

```
$ ./wkhtmltopdf.exe --encoding UTF-8 --no-outline --print-media-type -T 40 -R 25 -B 25 -L 25 --header-center he --header-font-size 10 --header-spacing 10 --footer-center Page [page] of [topage] --footer-font-size 10 --enable-local-file-access  --load-error-handling ignore src/test/resources/dtr_test.html /tmp/test.pdf
Loading pages (1/6)
Error: Failed to load http://of/, with network status code 2 and http status code 0 - Connection closed
Error: Failed loading page http://of (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: RemoteHostClosedError
```

**Comment by clemensutschig** [comment]
```
./wkhtmltopdf.exe ... --footer-center 'Page [page] of [topage]' ... 
```
note the `'` - makes me able to run the thing from the command line .. BUT ... still from groovy I get a hanging process ... :(

**Comment by clemensutschig** [comment]
PR contains a potential fix @carlosriess
